name: Check MFA Appointment

on:
  schedule:
    - cron: "*/30 * * * *"  # Toutes les 30 minutes
  workflow_dispatch:       # Pour l'exécuter manuellement depuis GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run check_slots.py
        run: python check_slots.py
